---
title: "ST 558 Blog Post Project 1"
author: "Rebecca Voelker"
---

## Prompt

•	Explain what you did in the project and any interesting findings
•	Reflect on the process – What was the most difficult part of the logic and programming? What would you do different in approaching a similar project in the future? 

## Relevant Links
**Please Note these Links will Not be Active / Functional Until Thursday, October 7th (i.e. Project Due Date)**

Link to COVID API Vignette:
Link to ST 558 Project 1 Repo: https://github.com/rlvoelke15/ST558Project1 

For this Project Assignment, I connected to and queried data from the COVID API. I was able to build multiple function calls, across different endpoints, to pull in various subsets of data. 

I then performed an exploratory data analysis on portions of my data. I focused specifically on COVID cases in North Carolina, as a region of interest, as well as Australia. 
I found that the rate of active cases across North Carolina, continues to increase over-time, which is consistent with what we are seeing nationwide. Australia has seen much lower rates of Confirmed COVID cases, as compared to the United States. COVID seems to be concentrated in New South Wales and Victoria, which is consistent with the fact that these are two of the most populous areas in the country. 

When reflecting on this process, I think the most difficult part of the logic was understanding the different endpoints and how those affected my datasets. It took a lot of time to explore and understand the difference between different URLs, as well as the ‘flexibility’ each had within it’s endpoints, to allow for user-defined interactions. 

It was also a bit tricky, given that so much of the data within the COVID API was numeric (i.e. # of Confirmed Cases, # of Deaths, etc.) AND cumulative. With this understanding I found myself creating multiple new variables (primarily, categorical) that would make my exploratory data analysis more meaningful! This project taught me not to limit myself to the data directly in front of me and to think about how I can use existing variables / datasets to create new variables, that might be of value! 

Overall, I found this to be an incredibly informative project, not just as it relates to interesting COVID-19 Data, but also for the purposes of continuing to build and expand my skill set within R!
